# GitHub Actions Workflow Optimization Configuration
# This file contains common configurations and optimizations for CI workflows

# Cache Configuration
cache:
  # Python dependencies cache
  pip_cache_key: "${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}"
  pip_cache_paths:
    - ~/.cache/pip
  
  # Node.js dependencies cache (if needed for docs)
  node_cache_key: "${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}"
  node_cache_paths:
    - ~/.npm
    - node_modules

# Timeout Configuration
timeouts:
  dependency_install: 15  # minutes
  test_execution: 20      # minutes
  security_scan: 10       # minutes
  build_process: 15       # minutes

# Parallel Execution Settings
parallelization:
  pytest_workers: "auto"  # Use pytest-xdist for parallel testing
  max_parallel_jobs: 3    # Limit concurrent jobs to avoid resource contention

# Python Versions
python_versions:
  - "3.11"
  - "3.12" 
  - "3.13"

# Common Dependencies
common_dev_dependencies:
  - pytest
  - pytest-cov
  - pytest-html
  - pytest-xdist
  - black
  - isort
  - flake8
  - mypy
  - bandit
  - safety

# Performance Optimizations
optimizations:
  # Use faster Ubuntu runner
  runner: "ubuntu-latest"
  
  # Skip unnecessary steps in certain conditions
  skip_conditions:
    - "contains(github.event.head_commit.message, '[skip ci]')"
    - "contains(github.event.head_commit.message, '[ci skip]')"
  
  # Artifact retention
  artifact_retention_days: 7
  
  # Concurrent job limits
  max_concurrent_jobs: 10

# Security Configuration
security:
  # SARIF upload for security results
  sarif_upload: true
  
  # Dependency vulnerability check
  vulnerability_check: true
  
  # Code scanning alerts
  code_scanning: true

# Notification Settings
notifications:
  # Slack webhook for failures (if configured)
  slack_on_failure: false
  
  # Email notifications
  email_on_failure: false
  
  # GitHub status checks
  required_status_checks:
    - "test-coverage"
    - "code-quality"
    - "security-scan"
    - "plugin-validation"
