name: Auto-format

on:
  push:
    branches: [ develop, feature/* ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort autoflake
    
    - name: Remove unused imports
      run: |
        echo "🧹 Removing unused imports..."
        autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive .
    
    - name: Sort imports
      run: |
        echo "📦 Sorting imports..."
        isort .
    
    - name: Format code
      run: |
        echo "🎨 Formatting code..."
        black .
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "style: auto-format code with black and isort" || echo "No changes to commit"
        git push
