name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    
    - name: Update dependencies
      run: |
        # Create requirements.in from current requirements.txt
        grep -E '^[a-zA-Z]' requirements.txt | sed 's/==.*//' > requirements.in
        
        # Compile new requirements with latest versions
        pip-compile --upgrade --resolver=backtracking requirements.in
        
        # Check if there are any changes
        if ! git diff --quiet requirements.txt; then
          echo "dependencies_updated=true" >> $GITHUB_ENV
        else
          echo "dependencies_updated=false" >> $GITHUB_ENV
        fi
    
    - name: Test updated dependencies
      if: env.dependencies_updated == 'true'
      run: |
        pip install -r requirements.txt
        python -c "import flask, openai, pandas, RapidFuzz, pytest; print('✅ All imports successful')"
        pytest tests/ --tb=short
    
    - name: Create Pull Request
      if: env.dependencies_updated == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Automated Dependency Update"
        body: |
          ## 📦 Dependency Updates
          
          This PR contains automated dependency updates:
          
          - ✅ Dependencies updated to latest compatible versions
          - ✅ All imports tested successfully
          - ✅ Test suite passed
          
          **Review the changes and merge if everything looks good.**
          
          ---
          *Generated by automated dependency update workflow*
        branch: chore/update-dependencies
        delete-branch: true
