name: Security Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install bandit
      - name: Run Bandit security scan
        run: |
          echo "🔒 Running security scan..."
          bandit -r . -c .bandit || echo "Security scan completed with findings"
          echo "✅ Security scan finished"
